spring:
  application.name: Product Service
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Use `validate` or `none` in prod, or Flyway for migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: off

  # Optional: use UTC everywhere
  jackson:
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
